### PR TITLE
Add basic authentication for admin actions

### PR DESCRIPTION
**Pull request by vgonda**
Worksighted would like authentication for admin actions such as managing users.

[[Finishes #149859218]](https://www.pivotaltracker.com/story/show/149859218)

### CODE REVIEW

**Comment by albus522** [comment]
Environment variables are not a straight forward option in the deploy environment. There is a settings file that could be used.

**Comment by albus522** [comment]
https://github.com/collectiveidea/bender/blob/master/lib/setting.rb

Probably also have the auth conditional based on a password actually set.

**Comment by vgonda** [comment]
Gotcha. Thanks for the info! I'll update to use that.

**Comment by vgonda** [comment]
Updated!

**Comment by albus522** [comment]
For the level of security we need this is fine. There is a more fine grained version that would allow us to store a digested password, but I don't think we need to go that far for this

**Pull request merged**
