### PR TITLE
An Admin can manage user

### PR DESCRIPTION
**Pull request by vgonda**
This adds CRUD for users. Editing and Deleting are only allowed if an authenticated admin.

### CODE REVIEW

**Comment by albus522** [comment]
Probably want to drop this in the admin section and have all the admin controllers inherit from `AdminController` for the new authentication requirement.

**Comment by vgonda** [comment]
I like that idea

**Comment by vgonda** [comment]
@albus522 Is this what you were thinking?

**Comment by albus522** [comment]
I would add the new and create to the admin section.

**Comment by vgonda** [comment]
We do not want new and create password protected. Would it be best to move them under admin, and exempt it from authentication? Or leave them here?

**Pull request merged**
